-- Haskell data types for the abstract syntax.
-- Generated by the BNF converter.

module Omnirev.AbsOmnirev where

newtype Ident = Ident String
  deriving (Eq, Ord, Show, Read)

data Program = Prog [Def]
  deriving (Eq, Ord, Show, Read)

data Def = DType Ident Type | DTerm Ident Type Expr
  deriving (Eq, Ord, Show, Read)

data Type
    = TyVar Ident
    | TyUnit
    | TySum Type Type
    | TyTensor Type Type
    | TyFunc Type Type
    | TyRec Ident Type
  deriving (Eq, Ord, Show, Read)

data Term
    = TmVar Ident
    | TmUnit
    | TmLeft Term
    | TmRight Term
    | TmTensor Term Term
    | TmArrow Term Term
    | TmFold Type Term
    | TmLin Term Term
    | TmLabel Ident Term
  deriving (Eq, Ord, Show, Read)

data Expr
    = ExTerm Term
    | ExApp Expr Term
    | ExComp Expr Expr
    | ExFlip Expr
    | ExTrace Term Ident Type
  deriving (Eq, Ord, Show, Read)

